### ISSUE TITLE
Give control over 'once' option for events

### ISSUE THREAD

**Issue by almostStatic** [discordjs-handler/source#1]
Discord.js provides a `on` or `once` emitter for events, eg

```js
client.on("name", Callback);
```

```js
client.once("name", Callback);
```

The latter only emits once, whereas the one before that can emit multiple times. It would be cool if there were an abillity to control this within the package - if there is, then please do correct me.

**Comment by bad-boy-discord** [comment]
**Hello, I don't understand the problem you want to tell me. There are no events in my module.**

**Comment by bad-boy-discord** [comment]
**If you wanted to write your problem to the repository of the module "discord.js" - here is the link: https://github.com/discordjs/discord.js**

**Comment by bad-boy-discord** [comment]
**I will close your request at the moment, there will be questions - write here.**
